### ISSUE TITLE
Color of the line going through the x's and o's is reversed

### ISSUE THREAD

**Issue by cyrusstoller** [kennycason/ultimate_tictactoe#1]
Great implementation! I've been playing with a few of my friends and have been having a great time on http://ken-soft.com/tictactoe/. 

In your last commit 53655b056835e480ab45f84c05c5ef7d2bc84455 when you made X go first, I think you forgot to switch the color line that goes through the x's and o's when you win a sub-board.

**Comment by cyrusstoller** [comment]
Submitted a PR

**Comment by kennycason** [comment]
@cyrusstoller Thanks! I noticed that, I fixed it as well, before I saw this issue

**Comment by kennycason** [comment]
Also, thanks for playing :), I created an AI issue as I am going to implement that in a day or so, it's already mostly implemented
