### ISSUE TITLE
Too much randomness...?

### ISSUE THREAD

**Issue by jimeh** [kennycason/ultimate_tictactoe#4]
I'm not sure if this is a feature or a bug. But my initial impression is that the game should force you to play 9 separate tic tac toe games at once, randomly switching between them.

The problem comes from how the random switching works. For example, when it's X's turn to play, it picks one of 9 games randomly, rather than limiting the random game choice only to games where it's X's turn. This leads to the winner being partly determined by random luck rather than tic tac toe skill.

For example, here's the game I played against myself:
![screen shot 2013-06-19 at 11 16 58](https://f.cloud.github.com/assets/39563/674010/7ff353f8-d8c9-11e2-86e6-8fccbd217af4.png)

The top right corner game is the worst offender, O had 4 plays, and X and only 1.

If this is intended behavior though, please ignore me :)

**Comment by kennycason** [comment]
@jimeh  no problem at all :) There is a link in the top of the README.md that has a linke to the rules. There is in fact not 9 concurrent games going on, but instead it's one giante game. So there is no sense of it's X's turn on grid (1,1) but O's turn on grid(0,0) for example. 

Also, the jumping around from board to board, isn't random, it's a tool that you can use to force you're opponent to move in other squares. 

As you probably noticed that even after a player claims victory in one 3x3 grid, the grid is still open for future moves. It can not be re-won/lost however. The game is won by a player winning 3 different 3x3 games in a row (horiz, vert, diag)

**Comment by jimeh** [comment]
oOo... okay, now that makes it much more interesting :D... I apologize for my ignorance :)

**Comment by kennycason** [comment]
@jimeh no problem! Thanks for the interest!
